branches:
  only:
    - master

language: python

env:
  - PYTHON_VERSION=2.7
  - PYTHON_VERSION=3.6

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - sudo apt-get -qq update
  - sudo apt-get install -y gsl-bin
  - sudo apt-get install -y libgsl0-dev
  # fix multiprocessing bugs on Travis
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

# install packages
install:
  - conda create --yes -n test python=$PYTHON_VERSION
  - source activate test
  - conda install --yes numpy scipy nose
  - pip install -r requirements.txt
  - python setup.py install

script: cd tests && nosetests
cache:
  pip: true

